title: 3 Frog Studio
description: We are making a game about cleaning a magic school!
remote_theme: pages-themes/slate@v0.2.0
show_downloads: true
wishlist_url: https://discord.gg/mFKzS7xkad
plugins:
- jekyll-remote-theme
